# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f5c63e0da28bd4d254c8a476713a3441bf414b2fa2c86f2b8f1ce766b887e6ed8aa3eca892262a25594f48d4378c83bb3c4a5b61be04bb0dd6e0b486441f2d2

test:
  secret_key_base: bbce0c28f85a63d5c9b4f5fb6f3880b1ed7b6cd14b21796b27f3f3b2f90e38b6c73d7b24db6d821822a905a8d8221a5d07303b88a71a3ea1fe92e8bf343e4d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
